### ISSUE TITLE
Add automated realeases via Github actions

### ISSUE THREAD

**Issue by tpokorra** [basxsoftwareassociation/basxconnect_demo#2]
once the python packages bread, htmlgenerator and basxconnect get more stable, we should just reference basxconnect without git repositories in requirements.txt.

**Comment by saemideluxe** [comment]
Okay, after using for some time I suggest the following:
- In custom projects (PWS, UM, etc) this is up to the responsible person and often we will want to use a rather up-to date version or a certain commit.
- For all packages/libraries we should be using the pip-package name as depency, but we are doing that already
- Since we do not have a fully automated pip-publishing process this can from time to time cause a bit problems

New task: Automatically create a new release when a new tag is pushed

**Comment by saemideluxe** [comment]
Okay, automating of releases is done.
