### ISSUE TITLE
Show information about celery configuration on a systeminformation page

### ISSUE THREAD

**Issue by tpokorra** [basxsoftwareassociation/basxconnect_demo#3]
@saemideluxe said:

> In order to have features available which are scheduled or task based, a celery worker needs to be started in addition:
> celery -A celery_config worker
> Since celery is a dependency, it should be available after pip install -r requirements.txt.
> And for the backend queue-system rabbitmq needs to installed and running (e.g. with apt install rabbitmq-server)

**Comment by saemideluxe** [comment]
Maybe some explanation why we want a task-queue instead of simple cron jobs:
- cronjobs have no guarantees regarding execution, e.g. things like: error reporting, result values, queuing of tasks, delayed execution of tasks
- a task scheduler integrates directly/better with language and framework, especially celery has a very nice and clear API
- cron-like-functionallity is still available
- asynchronous tasks/background processes come for free

The only downside is having to install and run rabbitmq. However, that is just a simple package installation on almost all systems, no configuration needed by default.

**Comment by saemideluxe** [comment]
I think we could extend the view bread.views.systeminformation to display whether celery is installed and running (if possible).

**Comment by saemideluxe** [comment]
Moved to https://github.com/basxsoftwareassociation/bread/issues/68
